import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  const deedsInfo = [
    {
      number: 60768,
      title: 'Body',
      theme: 'bodywork',
      description:
        'Here, we will train the body. Using mainly the techniques of breathwork and bodywork, we will make sure that the body is in a good condition to host an enhanced capacity to be in the present moment.',
    },
    {
      number: 84090,
      title: 'Mind',
      theme: 'Inner Work',
      description:
        'Training the ability to single point the mind using meditation as the tool. This is a silent deed, on which we will only sit and practice. ',
    },
    {
      number: 71810,
      title: 'Spirit',
      theme: 'Creativity',
      description:
        'The creative act is the ultimate expression of being human. In here, you will join other creators.  ',
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>The School Of Presence</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h2>The School of Presence</h2>
      <main className={styles.main}>
        <div className={styles.otherdeedsContainer}>
          {deedsInfo.map((x, i) => (
            <div key={i} className={styles.deedContainer}>
              <h3>{x.title}</h3>
              <Image
                src={`/images/${x.number}.jpeg`}
                width={333}
                alt={`Otherdeed number ${x.number}`}
                height={333 * 1.3}
              />
              <p>{x.description}</p>
            </div>
          ))}
        </div>
        <p>
          If you want to be up to date to how this project unfolds, follow me on
          twitter:{' '}
          <a
            href='https://www.twitter.com/kithkui'
            target='_blank'
            rel='noreferrer'
          >
            @kithkui
          </a>
        </p>
        <div className={styles.wtfIsThis}>
          {' '}
          <h2>WTF is this?</h2>
          <p>Good question. I&apos;ll start by telling you what it is not. </p>
          <p>
            It is not a place where you will come to rest. We will have fun by
            Doing The work. A system is being developed, a system for awakening
            the consciousness to humans that are ready for it. What does it mean
            to be ready? To have inside a burning desire to experience life from
            the truth of your being.
          </p>
          <p>
            There are two dimensions of reality: The absolute and The Relative.
            Everything that your mind comprehends from the world is part of the
            relative, of that which changes. Every eternal wisdom that has been
            developed by humans from different places in the world points
            towards the dimension that doesn&apos;t change. That which underlies
            each change. That which underlies the self.
          </p>
          <p>The ground of existence.</p>
          <p>
            This project is an exploration into a new way of connecting with
            that ground of self, by using the tools that our current technology
            gives us.{' '}
          </p>
          <p>
            By writing these words, I make a deep commitment to myself. To be
            open to create this world, and to serve as a vehicle for greater
            good. It is time for us to wake up.
          </p>
          <p>lfg</p>
        </div>
      </main>
    </div>
  );
}
